data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/user_data55/wangdq/data/ccmt/zh-en/parallel/zh.token"
    - "/home/user_data55/wangdq/data/ccmt/zh-en/parallel/en.token"
  valid_data:
    - "/home/user_data55/wangdq/data/ccmt/zh-en/dev2020/dev.zh.token"
    - "/home/user_data55/wangdq/data/ccmt/zh-en/dev2020/dev.en.token"
  bleu_valid_reference: "/home/user_data55/wangdq/data/ccmt/zh-en/dev2020/dev.en"
  vocabularies:
    - type: "bpe"
      dict_path: "/home/user_data55/wangdq/data/ccmt/zh-en/parallel/zh.vocab"
      max_n_words: -1
      codes: "/home/user_data55/wangdq/data/ccmt/zh-en/parallel/zh.code"
    - type: "bpe"
      dict_path: "/home/user_data55/wangdq/data/ccmt/zh-en/parallel/en.vocab"
      codes: "/home/user_data55/wangdq/data/ccmt/zh-en/parallel/en.code"
      max_n_words: -1
  max_len:
    - 100
    - 100
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: Transformer_Relative
  n_layers: 6
  n_head: 16
  d_word_vec: 1024
  d_model: 1024
  d_inner_hid: 4096
  dropout: 0.2
  proj_share_weight: true
  label_smoothing: 0.1
  ffn_activation: "gelu"

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.1
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 4000

training_configs:
  seed: 1234
  max_epochs: 100
  shuffle: true
  use_bucket: true
  batch_size: 4096
  batching_key: "tokens"
  update_cycle: 1
  valid_batch_size: 10
  disp_freq: 1000
  save_freq: 1000
  num_kept_checkpoints: 1
  loss_valid_freq: 1000
  bleu_valid_freq: 1000
  bleu_valid_batch_size: 5
  bleu_valid_warmup: 3
  bleu_valid_configs:
    max_steps: 150
    beam_size: 5
    alpha: 0.8
    sacrebleu_args: "--tokenize none"
    postprocess: true
  early_stop_patience: 30