data_configs:
  lang_pair: "en-de"
  train_data:
    - "/home/public_data/nmtdata/wmt14_en-de_data_selection/train.tok.clean.en"
    - "/home/public_data/nmtdata/wmt14_en-de_data_selection/train.tok.clean.de"
  valid_data:
    - "/home/public_data/nmtdata/wmt14_en-de_data_selection/newstest2013.tok.en"
    - "/home/public_data/nmtdata/wmt14_en-de_data_selection/newstest2013.tok.de"
  bleu_valid_reference: "/home/public_data/nmtdata/wmt14_en-de_data_selection/newstest2013.tok.de"
  vocabularies:
    - type: "bpe"
      max_n_words: -1
      dict_path: "/home/public_data/nmtdata/wmt14_en-de_data_selection/vocab.json"
      codes: "/home/public_data/nmtdata/wmt14_en-de_data_selection/bpe.32000"
      bpe_dropout: 0.1
    - type: "bpe"
      dict_path: "/home/public_data/nmtdata/wmt14_en-de_data_selection/vocab.json"
      codes: "/home/public_data/nmtdata/wmt14_en-de_data_selection/bpe.32000"
      max_n_words: -1
      bpe_dropout: 0.1
  max_len:
    - -1
    - -1
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 512
  d_model: 512
  d_inner_hid: 2048
  dropout: 0.1
  proj_share_weight: true
  label_smoothing: 0.1

  loss_configs:
    - type: "nmt_criterion"
      label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 50
  shuffle: true
  use_bucket: true
  batch_size: 2500
  batching_key: "tokens"
  update_cycle: 10
  valid_batch_size: 20
  disp_freq: 1000
  save_freq: 1000
  num_kept_checkpoints: 1
  loss_valid_freq: 1000
  bleu_valid_freq: 1000
  bleu_valid_batch_size: 5
  bleu_valid_warmup: 1
  bleu_valid_configs:
    max_steps: 150
    beam_size: 4
    alpha: 0.6
    postprocess: False
    sacrebleu_args: "--tokenize none -lc"
  early_stop_patience: 50
